name: 'HOCON Formatter'
description: 'Format hocon files'
author: 'jsoref'
branding:
  icon: 'edit-3'
  color: 'yellow'
inputs:
  artifact-name:
    description: 'Artifact name'
    default: ''
    required: false
  hocon-files:
    description: 'List of hocon files to format'
    required: false
  hocon-file-list:
    description: 'Null delimited file of hocon files to format'
    required: false
  indentation:
    description: 'Number of spaces to indent per level'
    default: '2'
    required: false
  parallel-tasks:
    description: 'Number of tasks to run concurrently (detected automatically unless specified)'
    default: ''
    required: false
  suppress-failure:
    description: 'If you do not want to fail when changes are required'
    default: ''
    required: false
  suppress-summary:
    description: 'If you do not want to generate a github step summary'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - id: format
      env:
        FILES: ${{ inputs.hocon-files }}
        LIST: ${{ inputs.hocon-file-list }}
        INDENTATION: ${{ inputs.indentation }}
        PARALLEL_TASKS: ${{ inputs.parallel-tasks }}
        SKIP_SUMMARY: ${{ inputs.suppress-summary }}
        MATRIX: ${{ toJSON(matrix) }}
      name: Format
      run: |
        : Format
        $GITHUB_ACTION_PATH/format.sh
      shell: bash
    - id: artifacts
      if: steps.format.outputs.files
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name || format('hocon-formatted-{0}-{1}-{2}', github.run_number, github.run_attempt, steps.format.outputs.id) }}
        path: ${{ steps.format.outputs.files }}
    - name: Fail
      if: steps.format.outputs.files && ! inputs.suppress-failure
      run: |
        : Fail
        exit 1
      shell: bash
